version: '3.1'

services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3306:3306
    volumes: 
      - ./database:/var/lib/mysql

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db  

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./www/:/www/
    links:
      - php
      
  php:
    image: php:7-fpm
    volumes:
      - ./www/:/www/
